config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :dividendos
  resources :saldos
  resources :bancos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/saldo/new', to: 'saldo#new'
  post '/saldo/create', to: 'saldo#create'
  match '/dividendos/:id/pagar', to: 'dividendos#pagar', via: [:get],  as: "pagar"
  root 'dashboards#index'
end

app/models/banco.rb
class Banco < ApplicationRecord
    has_many :saldos
    belongs_to :user
end

app/controllers/bancos_controller.rb
class BancosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_banco, only: [:show, :edit, :update, :destroy]

  # GET /bancos
  # GET /bancos.json
  def index
    @bancos = current_user.bancos.order(:nome, :tipo)
  end

  # GET /bancos/1
  # GET /bancos/1.json
  def show
  end

  # GET /bancos/new
  def new
    @banco = Banco.new
  end

  # GET /bancos/1/edit
  def edit
  end

  # POST /bancos
  # POST /bancos.json
  def create
    @banco = Banco.new(banco_params)
    @banco.user = current_user

    respond_to do |format|
      if @banco.save
        format.html { redirect_to @banco, notice: 'Banco was successfully created.' }
        format.json { render :show, status: :created, location: @banco }
      else
        format.html { render :new }
        format.json { render json: @banco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bancos/1
  # PATCH/PUT /bancos/1.json
  def update
    respond_to do |format|
      if @banco.update(banco_params)
        format.html { redirect_to @banco, notice: 'Banco was successfully updated.' }
        format.json { render :show, status: :ok, location: @banco }
      else
        format.html { render :edit }
        format.json { render json: @banco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bancos/1
  # DELETE /bancos/1.json
  def destroy
    @banco.destroy
    respond_to do |format|
      format.html { redirect_to bancos_url, notice: 'Banco was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_banco
      @banco = Banco.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def banco_params
      params.require(:banco).permit(:nome, :tipo)
    end
end

app/helpers/bancos_helper.rb
module BancosHelper

    def valor_atual_total(bancos)
        bancos.map{|b| ultimo_valor(b)}.to_a.sum
    end

    def ultimo_valor(banco)
        banco.saldos.sort_by{|s| s.data}.last.valor rescue 0
    end
end

app/views/bancos/_form.html.erb
<div class="card">
<%= form_with(model: banco, local: true) do |form| %>
  <% if banco.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(banco.errors.count, "error") %> prohibited this banco from being saved:</h2>

      <ul>
      <% banco.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col s12 m4">
      <%= form.label :nome %>
      <%= form.text_field :nome %>
    </div>

    <div class="col s12 m4">
      <%= form.label :tipo %>
      <%= form.text_field :tipo %>
    </div>
  </div>
  <div class="actions">
    <%= form.submit 'Salvar', class:"btn blue darken-4"%>
    <% if banco.id %>
      <%= link_to 'EXCLUIR', banco, method: :delete, data: { confirm: 'Tem certeza?' }, class: "btn red" %>
    <% end %>
  </div>
<% end %>
</div>

app/views/bancos/edit.html.erb
<h6>ALTERAR BANCO</h6>

<%= render 'form', banco: @banco %>

<div class="float-right">
    <%= link_to 'Detalhes', @banco, class:"btn blue darken-4" %>
    <%= link_to 'Outros bancos', bancos_path, class:"btn" %>
</div>

app/views/bancos/index.html.erb
<div class="title">
  <h6>BANCOS</h6>
  <%= link_to 'NOVO BANCO', new_banco_path, class: 'btn btn-primary accent-3' %>
</div>

<div class="bancos card">
  <div class="table">
    <ul class="head">
      <li class="columns">Nome</li>
      <li class="columns">Tipo</li>
      <li class="columns">Saldo Atual</li>
      <li class="columns"></li>
    </ul>
    <ul class="content">
     <% @bancos.each do |banco| %>
      <li class="row-table">
        <div class="columns"><span class="hide">Nome</span><%= link_to banco.nome.upcase, banco %></div>
        <div class="columns"><span class="hide">Tipo</span><%= banco.tipo %></div>
        <div class="columns"><span class="hide">Saldo Atual</span><%= number_to_currency ultimo_valor(banco) %></div>
        <div class="columns">
          <div class="btn-wrapper">
            <%= link_to 'EDITAR', edit_banco_path(banco), class: 'btn indigo accent-3' %>
            <%= link_to 'ADD', new_saldo_path(banco), class:"btn red"%>
          </div>
        </div>
      </li>
    <% end %>
     <li class="row-table">
        <div class="columns"><span class="hide"></span><b>Total</b></div>
        <div class="columns"></div>
        <div class="columns color-blue"><span class="hide"></span><b><%= number_to_currency valor_atual_total(@bancos)%></b></div>
        <div class="columns"></div>
      </li>
    </ul>
  </div>

</div>

<div class="fixed-action-btn">
  <%= link_to  saldo_new_path, class:"btn-floating btn-large waves-effect waves-light red" do%>
    <i class="material-icons">add</i>
  <% end %>
</div>
      

app/views/bancos/new.html.erb
<div class="title">
    <%= link_to bancos_path do %>
        <i class="material-icons">arrow_back</i> VOLTAR
    <%end%>
    <h6>NOVO BANCO</h6>
</div>

<%= render 'form', banco: @banco %>

app/views/bancos/show.html.erb
<div class="row">
  
  <%= link_to bancos_path, class:"" do %>
    <i class="material-icons">arrow_back</i> VOLTAR
  <% end %>
  <div class="float-right">
    <%= link_to edit_banco_path(@banco) do%> 
      <i class="material-icons">edit</i> EDITAR
    <%end%>
  </div>
  <h6>
    <%= @banco.nome.upcase %> 
  </h6>
  <small><%= @banco.tipo %></small>
</div>
<div class="card">
  <div class="grafic chart-panel" style="width: 100%;height:400px;" onclick="chart(this, 'Saldos',<%=  get_data_labels_banco(@banco) %>, <%= get_data_values_banco(@banco)%>, 'line');"></div>
  <table>
    <thead>
      <tr>
        <th>Data</th>
        <th>Valor</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @saldos_paginados = Kaminari.paginate_array(@banco.saldos.order('data DESC')).page(params[:page]).per(5) %>
      <% @saldos_paginados.each do |saldo| %>
        <tr>
          <td><%= saldo.data.strftime("%d/%m/%Y") %></td>
          <td><%= number_to_currency(saldo.valor) %></td>
          <td>
            <%= link_to edit_saldo_path(saldo) do %>
              <i class="material-icons">edit</i>
            <% end %>
            <%= link_to  saldo, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <i class="material-icons">delete</i>
            <%end%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>    
  <div class="page-description">
    <%= page_entries_info @saldos_paginados,  entry_name: 'Saldos' rescue nil %>
  </div>
  <%= paginate @saldos_paginados rescue nil %>
</div>
<br/>


<div class="fixed-action-btn">
  <%= link_to  new_saldo_path(@banco), class:"btn-floating btn-large waves-effect waves-light red" do%>
    <i class="material-icons">add</i>
  <% end %>
</div>
<script>
  document.querySelectorAll(".grafic").forEach(grafic => {
    grafic.click();
  });
</script>