config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :dividendos
  resources :saldos
  resources :bancos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/saldo/new', to: 'saldo#new'
  post '/saldo/create', to: 'saldo#create'
  match '/dividendos/:id/pagar', to: 'dividendos#pagar', via: [:get],  as: "pagar"
  root 'dashboards#index'
end

app/models/dividendo.rb
class Dividendo < ApplicationRecord

    belongs_to :user
    belongs_to :categoria
    
end

app/controllers/dividendos_controller.rb
class DividendosController < ApplicationController
  before_action :set_dividendo, only: [:show, :edit, :update, :destroy, :pagar]

  # GET /dividendos
  # GET /dividendos.json
  def index
    @competencia_atual = params[:dividendo][:competencia] rescue Date.today.strftime("%Y-%m")
    @competencia_atual =  Date.today.strftime("%Y-%m") if @competencia_atual.nil? || @competencia_atual.empty?
    @dividendos = current_user.dividendos.select{|d| d.competencia.strftime("%Y-%m") == @competencia_atual}.sort_by{|v| v.data_vencimento || Date.today()}.sort_by{|v| v.pago? ? 1:0} rescue []
  end

  # GET /dividendos/1
  # GET /dividendos/1.json
  def show
  end

  # GET /dividendos/new
  def new
    @dividendo = Dividendo.new
    @dividendo.competencia = Date.today
  end
  
  # GET /dividendos/1/edit
  def edit
  end
  
  # POST /dividendos
  # POST /dividendos.json
  def create
    @dividendo = Dividendo.new(dividendo_params)
    @dividendo.competencia = Date.parse(params[:dividendo][:competencia])
    @dividendo.user = current_user
    @dividendo.pago = false

    respond_to do |format|
      if @dividendo.save
        format.html { redirect_to dividendos_path, notice: 'Dividendo was successfully created.' }
        format.json { render :show, status: :created, location: @dividendo }
      else
        format.html { render :new }
        format.json { render json: @dividendo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dividendos/1
  # PATCH/PUT /dividendos/1.json
  def update
    respond_to do |format|
      if @dividendo.update(dividendo_params)
        @dividendo.competencia = Date.parse(params[:dividendo][:competencia])
        @dividendo.pago ||= false
        @dividendo.save
        format.html { redirect_to dividendos_path, notice: 'Dividendo was successfully updated.' }
        format.json { render :show, status: :ok, location: @dividendo }
      else
        format.html { render :edit }
        format.json { render json: @dividendo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dividendos/1
  # DELETE /dividendos/1.json
  def destroy
    @dividendo.destroy
    respond_to do |format|
      format.html { redirect_to dividendos_url, notice: 'Dividendo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /dividendos/:id/pagar
  def pagar
    @dividendo.pago = true
    respond_to do |format|
      if @dividendo.save()
        format.html { redirect_to dividendos_path, notice: 'Dividendo pago com sucesso.' }
        format.json { render :show, status: :ok, location: @dividendo }
      else
        format.html { render :edit }
        format.json { render json: @dividendo.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dividendo
      @dividendo = Dividendo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dividendo_params
      params.require(:dividendo).permit(:competencia, :descricao, :pago, :valor, :data_vencimento, :categoria_id)
    end

end

app/helpers/dividendos_helper.rb
module DividendosHelper

    def valor_total(dividendos)
        dividendos.map{|d| d.valor}.sum rescue 0
    end

    def valor_total_pago(dividendos)
        dividendos.select{|d| d.pago }.map{|d| d.valor}.sum rescue 0
    end

    def media_de_gastos
        dividendos = current_user.dividendos
        total = dividendos.map{|d|d.valor}.sum 
        meses = dividendos.map{|d|d.competencia.strftime("%m/%Y") }.to_set.count
        total / meses rescue 0
    end

    def competencia_atual
        Date.today().strftime("%m/%Y")
    end
end

app/views/dividendos/_form.html.erb
<div class="card">
<%= form_with(model: dividendo, local: true) do |form| %>
  <% if dividendo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dividendo.errors.count, "error") %> prohibited this dividendo from being saved:</h2>

      <ul>
      <% dividendo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
      <div class="col s12 m2">
        <%= form.label :competencia %>
        <%= form.text_field :competencia, class:"datepicker-competencia" %>
      </div>

      <div class="col s12 m2">
        <%= form.label :data_vencimento %>
        <%= form.text_field :data_vencimento, class:"datepicker-data" %>
      </div>

      <div class="col s12 m3">
        <%= form.label :categoria_id %>
        <%= form.select :categoria_id, Categoria.all.order(:nome).collect {|c| [c.nome, c.id]}, {:prompt => 'Selecione uma categoria'}, class:"browser-default" %>
      </div>

      <div class="col s12 m3">
        <%= form.label :descricao %>
        <%= form.text_field :descricao %>
      </div>

      <div class="col s12 m2">
        <%= form.label :valor %>
        <%= form.number_field :valor, step: '0.01' %>
      </div>
  </div>
 <div class="actions">
    <%= form.submit 'SALVAR', class:"btn blue darken-4" %>
    <% if dividendo.id %>
      <%= link_to 'EXCLUIR', dividendo, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn red" %>
    <% end %>
  </div>
<% end %>
</div>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.datepicker-competencia');
    var do_controller = '<%= @dividendo.competencia.strftime("%m-01-%Y") %>';
    var competencia_atual = new Date(do_controller);
    competencia_atual.setDate = 1;
    var options =  {format: 'mm/yyyy', disableWeekends: true, setDefaultDate: true, defaultDate: competencia_atual, autoClose: true, selectMonths: true}
    var instances = M.Datepicker.init(elems, options);
  });

  document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.datepicker-data');
    var do_controller = '<%= @dividendo.data_vencimento.strftime("%m-%d-%Y") rescue Date.today() %>';
    var competencia_atual = new Date(do_controller);
    var options =  {format: 'dd/mm/yyyy', disableWeekends: true, setDefaultDate: true, defaultDate: competencia_atual, autoClose: true, selectMonths: true}
    var instances = M.Datepicker.init(elems, options);
  });

</script>
      

app/views/dividendos/edit.html.erb
<%= link_to dividendos_path do %>
    <i class="material-icons">arrow_back</i> VOLTAR
<%end%>
<h6>ALTERAR DIVIDENDO</h6>

<%= render 'form', dividendo: @dividendo %>

app/views/dividendos/index.html.erb
<h6>DIVIDENDOS
  <div class="float-right btn-pesquisar">
    <i class="material-icons">search</i>
  </div>
  <br/>
  <small>Competência: <%= competencia_atual() %></small>
</h6>

<div id="card-search" class="row card hide">
  <div class="col m3">
    <%= form_tag("/dividendos", method: "get") do %>
      <%= label_tag(:q, "Competência:") %>
      <%= month_field(:dividendo, :competencia) %>
  </div>  
  <div class="col m3"></div>
  <div class="col m3"></div>
  <div class="col m3 pesquisar">
    <%= submit_tag 'Pesquisar', class:"btn btn-primary" %>
  </div>
    <% end %>  
</div>


<div class="card dividendos">
 <div class="table">
    <ul class="head">
      <li class="columns">Categoria</li>
      <li class="columns">Descrição</li>
      <li class="columns">Vencimento</li>
      <li class="columns">Valor</li>
      <li class="columns">Ações</li>
    </ul>

    <ul class="content">
    
    <% @dividendos.each do |dividendo| %>
      <li class="row-table">  
        <div class="columns"><span class="hide"><b>Categoria</b></span><%= dividendo.try(:categoria).try(:nome) %></div>
        <div class="columns"><span class="hide"><b>Descrição</b></span><%= dividendo.descricao %></div>
        <div class="columns"><span class="hide"><b>Vencimento</b></span><%= dividendo.data_vencimento.strftime("%d/%m/%Y") rescue nil %></div>
        <div class="columns"><span class="hide"><b>Valor</b></span><%= number_to_currency dividendo.valor %></div>
        <div class="columns">
          <div class="btn-wrapper">
            <%= link_to 'editar', edit_dividendo_path(dividendo), class: 'btn indigo accent-3' %>
            <%if(dividendo.pago?) %>
              <%= link_to 'PAGO', '#', class: 'btn disabled' %>
            <% else %>
              <%= link_to 'PAGAR', pagar_path(dividendo), class: 'btn btn-primary' %>
            <% end %>
          </div>
        </div>
      </li>
    <% end %>
     <li class="row-table">
     <div class="columns"><span class="hide"></span><b>Total</b></div>
        <div class="columns"><span class="hide"></span></div>
        <div class="columns color-red"><span class="hide">Devendo</span><b><%= number_to_currency valor_total_pago(@dividendos) - valor_total(@dividendos)%></b></div>
        <div class="columns color-green"><span class="hide">Pago</span><b><%= number_to_currency valor_total_pago(@dividendos)%></b></div>
        <div class="columns color-blue"><span class="hide">Total</span><b><%= number_to_currency valor_total(@dividendos)%></b></div>
      </li>
    </ul>
  </div>


<div class="page-description">
    <%= page_entries_info @dividendos rescue nil %>
  </div>
  <%= paginate @dividendos rescue nil %>
</div>

<div class="fixed-action-btn">
  <%= link_to  new_dividendo_path, class:"btn-floating btn-large waves-effect waves-light red" do%>
    <i class="material-icons">add</i>
  <% end %>
</div>

<script>

$(".btn-pesquisar").click(function(e){
  if ($("#card-search").hasClass("hide")){
    $("#card-search").removeClass("hide")
  }else{
    $("#card-search").addClass("hide")
  }
})

</script>

app/views/dividendos/new.html.erb
<div class="title">
    <%= link_to dividendos_path do %>
        <i class="material-icons">arrow_back</i> VOLTAR
    <%end%>
    <h6>NOVO DIVIDENDO</h6>
</div>
<%= render 'form', dividendo: @dividendo %>

app/views/dividendos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descricao:</strong>
  <%= @dividendo.descricao %>
</p>

<p>
  <strong>Pago:</strong>
  <%= @dividendo.pago %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @dividendo.valor %>
</p>

<%= link_to 'Edit', edit_dividendo_path(@dividendo) %> |
<%= link_to 'Back', dividendos_path %>