config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :dividendos
  resources :saldos
  resources :bancos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/saldo/new', to: 'saldo#new'
  post '/saldo/create', to: 'saldo#create'
  match '/dividendos/:id/pagar', to: 'dividendos#pagar', via: [:get],  as: "pagar"
  root 'dashboards#index'
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user! 
  # GET /dashboards
  # GET /dashboards.json
  def index
    @bancos = current_user.bancos.order(:nome)
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper

    def get_data_labels_banco(banco)
        banco.saldos.sort_by{|s| s.data}.map{|s| s.data.strftime("%d/%m/%y")}.to_set.to_a
    end

    def get_data_values_banco(banco)
        banco.saldos.to_a.map{|s| [s.data, s.valor]}.sort.to_h.values
    end

    def get_data_labels_user(user)
        user.bancos.map{|b| b.saldos.group_by{|s|s.data}.keys}.flatten.to_set.sort.map{|d| d.strftime("%d/%m/%y")}
    end

    def get_data_values_user(user)
        Saldo.where(:banco=>user.bancos.map{|b|b.id}).sort_by{|s|s.data}.group_by{|s| s.data}.map{|a| a[1].map{|s|s.valor}.sum}
    end

    def data_saldo_atual
        ultimo_dia_saldo.keys.first rescue ""
    end

    def saldo_atual
        ultimo_dia_saldo.values.first rescue 0
    end

    def ultimo_dia_saldo
        sql = "select
                s.data,
                sum(s.valor) as total
               from saldos s
                    inner join bancos b on s.banco_id = b.id
                    inner join users u on b.user_id = u.id
               where u.id = #{current_user.id}
               group by s.data
               order by s.data desc
               limit 1 
            "
        result = ActiveRecord::Base.connection.execute(sql)
        Hash[*result.first.values.to_set.to_a]
    end

    def format_data(string)
        Date.parse(string).strftime('%d/%m/%Y') rescue ""
    end

    def get_data_labels_dividendos(user)
        user.dividendos.sort_by{|d|d.competencia}.group_by{|d|d.competencia}.keys.to_set.map{|k| k.strftime("%m/%Y")}
    end

    def get_data_values_dividendos(user)
        user.dividendos.sort_by{|d|d.competencia}.group_by{|d|d.competencia}.values.map{|d|d.map{|s| s.valor}.sum}
    end

    def gasto_atual()
        competencia_atual = Date.today.strftime("%Y-%m")
        current_user.dividendos.select{|d| d.competencia.strftime("%Y-%m") == competencia_atual}.map{|d| d.valor}.sum
    end

    def get_data_labels_categorias(user)
        user.dividendos.group_by{|d|d.try(:categoria).try(:nome)}.keys.uniq
        # current_user.dividendos.sort_by{|d|d.try(:categoria).try(:nome)}.group_by{|d|d.try(:categoria).try(:nome)}.keys
    end

    def get_data_values_categorias(user)
        user.dividendos.group_by{|d|d.try(:categoria).try(:nome)}.map{ |k| { name: k[0], value: k[1].map{ |s| s.valor }.sum } }.to_json
        # current_user.dividendos.sort_by{ |d| d.try(:categoria).try(:nome) }.group_by{ |d| d.try(:categoria).try(:nome) }.map{ |k| { name: k[0], value: k[1].map{ |s| s.valor }.sum } }.to_json
    end
end

app/views/dashboards/_bancos.html.erb
<h6>
BANCOS
<div class="float-right">
  <i class="material-icons" onclick="hide($('.bancos'));">insert_chart</i>
</div>
</h6>

<div class="row bancos">
<% @bancos.each do |banco| %>
  <div class="col s12 m4">
    <div class="card">
      <div class="card-image">
        <div class="grafic chart-panel" style="width: 100%;height:200px;" onclick="chart(this, 'Saldos',<%=  get_data_labels_banco(banco) %>, <%= get_data_values_banco(banco)%>, 'line');"></div>
        <%= link_to new_saldo_path(banco), class:"btn-floating halfway-fab waves-effect waves-light red" do %>
          <i class="material-icons">add</i>
        <% end %>
      </div>
      <div class="card-content">
        <div style="align-items: center; text-align: center;"><span class="card-title"><%= link_to banco.nome, banco_path(banco.id) %></span></div>
        <small><%= banco.tipo %></small>
        <p>Saldo Atual: <%=number_to_currency( ultimo_valor(banco)) %> </p>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/dashboards/_categorias.html.erb
<div style="align-items: center; text-align: center;">
  <span class="card-title">Gastos por Categoria</span>
</div>
<div class="grafic" style="width: 100%;height:500px;" onclick="chartPie(this, 'Categorias', <%=  get_data_labels_categorias(current_user) %>, '<%= j get_data_values_categorias(current_user)%>');"></div>
<div class="card-content">

</div>

app/views/dashboards/_dividendos.html.erb
<div style="align-items: center; text-align: center;"><span class="card-title">Dividendos</span></div>
<div class="grafic chart-panel" style="width: 100%;height:200px;" onclick="chart(this, 'Dividendos',<%=  get_data_labels_dividendos(current_user) %>, <%= get_data_values_dividendos(current_user)%>, 'bar');"></div>
<div class="card-content">
    <p>Mês atual: <%= Date.today.strftime("%m/%Y") %> </p>
    <p>Gasto atual: <%=number_to_currency( gasto_atual()) %> -
     Média: <b><%= number_to_currency media_de_gastos()%></b></p>
</div>

app/views/dashboards/_graficos.html.erb
<h6>DASHBOARDS
  <div class="float-right">
    <i class="material-icons" onclick="hide($('.graficos'));">insert_chart</i>
  </div>
</h6>

<div class="row graficos">
  <div class="col m1"></div>
  <div class="card col m5">
    <%= render '/dashboards/saldos_bancario' %>
  </div>

  <div class="col m1"></div>
  <div class="card col m5">
    <%= render '/dashboards/dividendos' %>
  </div>
</div>

<div class="row graficos">
  <div class="col m1"></div>
  <div class="card col m11">
    <%= render '/dashboards/categorias' %>
  </div>
</div>

app/views/dashboards/_saldos_bancario.html.erb
<div style="align-items: center; text-align: center;"><span class="card-title">Saldos Bancários</span></div>

<div class="grafic chart-panel grafico_saldo" style="width: 100%;height:200px;" onclick="chart(this, 'Saldos',<%=  get_data_labels_user(current_user) %>, <%= get_data_values_user(current_user)%>, 'bar');"></div>
<div class="card-content">
    <p>Data Atual: <%= format_data(data_saldo_atual()) %> </p>
    <p>Saldo Atual: <%=number_to_currency( saldo_atual()) %> </p>
</div>

app/views/dashboards/index.html.erb
<% if @bancos.empty? %>
  <div style="align-items: center; text-align: center;">
    <%= image_tag(asset_url('bank_empty.png'), alt: "Nenhum banco cadastrado no sistema.") %>
    <p>Não há bancos cadastrados, clique em + no canto direito para iniciar.<p>
  </div>
<% else %>
  <%= render '/dashboards/graficos' %>
  <%= render '/dashboards/bancos' %>
<% end %>

<div class="fixed-action-btn">
  <%= link_to  new_banco_path, class:"btn-floating btn-large waves-effect waves-light red" do%>
    <i class="material-icons">add</i>
  <% end %>
</div>

<script>
  document.querySelectorAll(".grafic").forEach(grafic => {
    grafic.click();
  });

  $(".label_banco").click(function(){
    let bancos = $(".bancos")
    if(bancos.hasClass("hide")){
      bancos.removeClass("hide")
    }else{
      bancos.addClass("hide")
    }
  });

</script>