config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :dividendos
  resources :saldos
  resources :bancos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/saldo/new', to: 'saldo#new'
  post '/saldo/create', to: 'saldo#create'
  match '/dividendos/:id/pagar', to: 'dividendos#pagar', via: [:get],  as: "pagar"
  root 'dashboards#index'
end

app/views/layouts/_nav_bar.html.erb
<div class="navbar-fixed">
  <nav class="blue">
    <%= render 'layouts/side_bar' %>
    <div class="nav-wrapper">
      <a href="/" class="brand-logo">Carteira</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <% if current_user %>
        <li><%= link_to 'Bancos', bancos_path %></li>
        <li><%= link_to 'Dividendos', dividendos_path %></li>
        <li><%= link_to 'Saldos Diários', saldos_path %></li>
        <li>Olá, <%= current_user.email %></li>
        <li>
            <a  class='dropdown-trigger' href="#" data-target='dropdown1'><i class="material-icons">arrow_drop_down</i></a>
            <ul id='dropdown1' class='dropdown-content'>
              <li><%= link_to 'Sair', destroy_user_session_path, method: :delete %></li>
            </ul>
        </li>
        <%else%>
          <li><%= render "devise/shared/links" %></li>
        <%end%>
      </ul>
    </div>
  </nav>
</div>
<script>

$('.dropdown-trigger').dropdown();

</script>

app/views/layouts/_side_bar.html.erb
 <ul id="slide-out" class="sidenav">
 <% if current_user %>
  <li>
    <a href=""><span class="white-text email"><%= current_user.email%></span></a>
  </li>
  <li><%= link_to 'Dashboard', root_path %></li>
  <li><%= link_to 'Bancos', bancos_path %></li>
  <li><%= link_to 'Dividendos', dividendos_path %></li>
  <li><%= link_to 'Saldos Diários', saldos_path %></li>
  <li><div class="divider"></div></li>
  <li><%= link_to 'Sair', destroy_user_session_path, method: :delete %></li>
<% else %>
  <li><%= render "devise/shared/links" %></li>
<% end %>
</ul>

<a href="#" data-target="slide-out" class="sidenav-trigger"><i class="material-icons">menu</i></a>
<script>
document.addEventListener('DOMContentLoaded', function() {
  var elems = document.querySelectorAll('.sidenav');
  var instances = M.Sidenav.init(elems);
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Carteira</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no">
  <link rel="manifest" href="/manifest.json" />
  <meta name="apple-mobile-web-app-capable" content="yes"></head>
  <%= javascript_include_tag 'application'%>
</head>
<body>

  <%= render 'layouts/nav_bar'%>   

  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <% if notice %>
          <p id="notice" class="flash_sucess"><%= notice %></p>
        <%end %>

        <% if alert %>
          <p class="flash_fail"><%= alert %></p>
        <%end%>
      </div>
    </div>
    <div class="row">

      <%= yield %>      

    </div>
  </div>
</body>
</html>